In [ ]:
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt
print(torch.__version__)
print(np.__version__)


2.10.0+cu128
2.0.2


# Introduction to Tensors
## Creating tensors

To create a pytorch tensor use:
  `torch.tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [ ]:
# Scalar
scalar = torch.tensor(7)
print(scalar.ndim)
# To extract the tensor values as python int use:
scalar.item()

0


7

In [ ]:
# Vector <=> 1 []-bracket
vector = torch.tensor([7,7])
print(vector.ndim)
print(vector.shape)
print(vector.size())


1
torch.Size([2])
torch.Size([2])


In [ ]:
# Matrix <=> 2 []-brackets
matrix = torch.tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
print(matrix.ndim)
print(matrix.shape)
# Extract value from a 2D tensor
tensor_1d = matrix[1,:]
print(tensor_1d)

2
torch.Size([3, 3])
tensor([4, 5, 6])


In [ ]:
# Image with color <=> 3 []-brackets
TENSOR = torch.tensor([[[1,2],
                        [4,5],
                        [7,8]]])
print(f"The dimension of TENSOR is {TENSOR.ndim}")
print(f"The size of TENSOR is {TENSOR.shape}")
TENSOR[0]

# For a mxnxp tensor:
#   - m <=> the channel
#   - n <=> the rows
#   - p <=> the cols


The dimension of TENSOR is 3
The size of TENSOR is torch.Size([1, 3, 2])


tensor([[1, 2],
        [4, 5],
        [7, 8]])

## Random tensors

Random tensors are important for the initialization step of neural network training. The initialized, random tensors are then update throughout the training process

To create a random tensor use:
- `torch.rand(size)` https://docs.pytorch.org/docs/stable/generated/torch.rand.html#torch-rand

In [ ]:
# Create a random 1d tensor
tensor_1d_rand = torch.rand(5) # This should give a 1x5 vector
print(tensor_1d_rand)

# Create a random 2d tensor with a shape of 3x2
tensor_2d_rand = torch.rand(3,2)
print(tensor_2d_rand)

# Create a random 3d tensor with a shape of 1x4x2
tensor_3d_rand = torch.rand(1,4,2)
print(tensor_3d_rand)

tensor([0.0820, 0.0140, 0.8331, 0.7976, 0.8320])
tensor([[0.8332, 0.2110],
        [0.8318, 0.9263],
        [0.0103, 0.9015]])
tensor([[[0.7283, 0.5007],
         [0.6764, 0.0497],
         [0.4972, 0.2162],
         [0.5069, 0.3413]]])


In [ ]:
# Create a random tensor with similar shape to an image
tensor_rand_imgSize = torch.rand(size=[3,640,640]) # channels, rows, cols
tensor_rand_imgSize.shape,tensor_rand_imgSize.ndim

(torch.Size([3, 640, 640]), 3)

## Zeros and Ones Tensors
To create a zeros tensor with ndims use:
- `torch.zeros(size)` https://docs.pytorch.org/docs/stable/generated/torch.zeros.html#torch.zeros

To create a ones tensor with ndims use:
-  `torch.ones(size)`

In [ ]:
# Create a 3x4 zeros tensor
tensor_zeros = torch.zeros(size=[3,4])
tensor_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a 3x4 ones tensor
tensor_ones = torch.ones(size=[3,4])
tensor_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Create tensor within a value range
To specify a range value for a tensor use:
- `torch.arange(start=,end=,step=)` https://docs.pytorch.org/docs/stable/generated/torch.arange.html#torch-arange

In [ ]:
# Create a tensor from 1-20
tensor_range = torch.arange(start=1,end=21)
tensor_range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

In [ ]:
# Creat tensors-like <=> a zeros or ones tensor that have the shape of another tensor
tensor_ten_zeros = torch.zeros_like(input=tensor_range)
tensor_ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatype

**Note:** Tensor datatype is one of the big 3 issues that you'll often run into with PyTorch & DeepLearning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
# float32 tensor
tensor_float32 = torch.tensor([3.0,6.0,9.0],
                              dtype=None, # What datatype is the tensor, e.g. float32, complex32. Define how much memory is used to precisely present a number
                              device=None, # Define which device (e.g. cpu or gpu or gpu1,etc) this tensor is created and stored
                              requires_grad=False) # wether or not to track gradients with this tensor operation
tensor_float32.dtype

torch.float32

In [ ]:
# Change the dtype of a tensor
tensor_float16 = tensor_float32.type(torch.float16)
tensor_float16.dtype

torch.float16

In [ ]:
tensor_float16*tensor_float32

tensor([ 9., 36., 81.])

In [ ]:
tensor_complex32 = torch.tensor([3,6,9],
                            dtype=torch.complex32)
tensor_float32*tensor_complex32


/tmp/ipykernel_1511/3830746781.py:1: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at /pytorch/aten/src/ATen/EmptyTensor.cpp:54.)
  tensor_complex32 = torch.tensor([3,6,9],


tensor([ 9.+0.j, 36.+0.j, 81.+0.j])

## Get information from tensors
1. Tensors not right datatype -> To get tensor dtype use: `tensor.dtype`
2. Tensors not right shape -> To get tensor shape use: `tensor.shape`
3. Tensors not on right device -> To get tensor's device use: `tensor.device`

In [ ]:
# Create a random tensor
tensor_random = torch.rand(size=[3,4])
tensor_random

tensor([[0.0131, 0.7582, 0.2375, 0.7667],
        [0.2242, 0.2383, 0.9168, 0.4427],
        [0.8796, 0.6857, 0.4222, 0.0759]])

In [ ]:
# Extract information from the tensor
print(f"The datatype of tensor_random is {tensor_random.dtype}")
print(f"The shape of tensor_random is {tensor_random.shape}")
print(f"The device of tensor_random is {tensor_random.device}")

The datatype of tensor_random is torch.float32
The shape of tensor_random is torch.Size([3, 4])
The device of tensor_random is cpu


## Tensor Operations

Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [ ]:
# Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [ ]:
# Multiply by 10
print(tensor * 10)
print(torch.mul(tensor,10))

tensor([10, 20, 30])
tensor([10, 20, 30])


In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Element-wise multiplication
tensor*tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
print(torch.matmul(tensor,tensor))
print(tensor@tensor)

tensor(14)
tensor(14)


### One of the most common in deep learning is SHAPE ERROR

In [ ]:
# Create tensors for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
# torch.matmul(tensor_A,tensor_B)

In [ ]:
# Transpose a matrix use:
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [ ]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finding the min, max, mean, sum, etc (Tensor Aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0,100,10,dtype=torch.float32)


In [ ]:
# Determine the max of tensor x
torch.max(x),x.max()

(tensor(90.), tensor(90.))

In [ ]:
# Determine the min of x
x.min(),torch.min(x)

(tensor(0.), tensor(0.))

In [ ]:
# Determine the mean of x - Note: torch.mean() function requires torch.float dtype
x.mean(),torch.mean(x)

(tensor(45.), tensor(45.))

In [ ]:
# Determine the total sum of x
x.sum(),torch.sum(x)

(tensor(450.), tensor(450.))

## Find the min/max position/index
To find the index of the min value use:
- `tensor.argmin()` => min_value = tensor[`tensor.argmin()`]

To find the index of the max value use:
- `tensor.argmax()` => max_value = tensor[`tensor.argmin()`]

In [ ]:
# Find the index position of the min value of x <=> Output is a index value
x.argmin()

tensor(0)

In [ ]:
# Find the index position of the max value of x
x.argmax()

tensor(9)

In [ ]:
# Extract the max value using indexing
x[x.argmax()]

tensor(90.)

## Tensor Shape Manipulation
* Reshaping - reshape an input tensor to a defined shape -> `tensor.reshape(shape)`
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor - > `tensor.view()`
* Stacking - Combine multiple tensor on top of each other (`torch.stack((tensor1,tensor2,...),dim=0)`) or side-by-sid (`torch.stack((tensor1,tensor2,..,dim=1)`)
* Squeez - removes all `1` dimensions from a tensor -> `tensor.squeeze()`
* Unsqueeze - add a `1` dimension to a target tensor -> `tensor.unsqueeze(dim)`
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way -> `tensor.permute(dims=[])`

In [ ]:
# Create a tensor
tensor_x = torch.arange(1.,11.)
tensor_x, tensor_x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# Add an extra dimension/ Reshaping the tensor
tensor_x_reshaped = tensor_x.reshape(5,2)
tensor_x_reshaped,tensor_x_reshaped.shape


(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
# Change the view
tensor_y = tensor_x.view(2,5)
tensor_y,tensor_y.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
# Change y <=> change x but the shape of x doesn't change only its corr. value
tensor_y[0,:] = 5
tensor_y,tensor_x

(tensor([[ 5.,  5.,  5.,  5.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  5.,  5.,  5.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# Stacking tensors along dim=0
tensor1 = torch.randn(5,3)
tensor1_stacked_dim0 = torch.stack((tensor1,tensor1),dim=0)
tensor1_stacked_dim0,tensor1_stacked_dim0.shape

(tensor([[[-0.2334, -1.8271,  0.2793],
          [-0.8222, -0.1243,  0.3780],
          [-0.8882, -0.1343, -0.0390],
          [ 0.7135,  1.2501,  1.3930],
          [ 1.1941, -0.7755, -0.0357]],
 
         [[-0.2334, -1.8271,  0.2793],
          [-0.8222, -0.1243,  0.3780],
          [-0.8882, -0.1343, -0.0390],
          [ 0.7135,  1.2501,  1.3930],
          [ 1.1941, -0.7755, -0.0357]]]),
 torch.Size([2, 5, 3]))

In [ ]:
# Stacking tensors along dim=1
tensor1_stacked_dim1 = torch.stack((tensor1,tensor1),dim=1)
tensor1_stacked_dim1,tensor1_stacked_dim1.shape

(tensor([[[-0.2334, -1.8271,  0.2793],
          [-0.2334, -1.8271,  0.2793]],
 
         [[-0.8222, -0.1243,  0.3780],
          [-0.8222, -0.1243,  0.3780]],
 
         [[-0.8882, -0.1343, -0.0390],
          [-0.8882, -0.1343, -0.0390]],
 
         [[ 0.7135,  1.2501,  1.3930],
          [ 0.7135,  1.2501,  1.3930]],
 
         [[ 1.1941, -0.7755, -0.0357],
          [ 1.1941, -0.7755, -0.0357]]]),
 torch.Size([5, 2, 3]))

In [ ]:
tensor1_stacked_dim2 = torch.stack((tensor1,tensor1),dim=2)
tensor1_stacked_dim2,tensor1_stacked_dim2.shape

(tensor([[[-0.2334, -0.2334],
          [-1.8271, -1.8271],
          [ 0.2793,  0.2793]],
 
         [[-0.8222, -0.8222],
          [-0.1243, -0.1243],
          [ 0.3780,  0.3780]],
 
         [[-0.8882, -0.8882],
          [-0.1343, -0.1343],
          [-0.0390, -0.0390]],
 
         [[ 0.7135,  0.7135],
          [ 1.2501,  1.2501],
          [ 1.3930,  1.3930]],
 
         [[ 1.1941,  1.1941],
          [-0.7755, -0.7755],
          [-0.0357, -0.0357]]]),
 torch.Size([5, 3, 2]))

In [ ]:
# Squeezing
tensor_x_reshaped

tensor([[ 5.,  5.],
        [ 5.,  5.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
tensor_x_reshaped.squeeze()

tensor([[ 5.,  5.],
        [ 5.,  5.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
# Create a tensor with unneccesary 1d array
tensor_a = torch.zeros(size=[1,1,9])
tensor_a, tensor_a.shape

(tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0.]]]), torch.Size([1, 1, 9]))

In [ ]:
tensor_a_squeezed = tensor_a.squeeze()
tensor_a_squeezed

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# torch.unsqueeze() - adds a single dim to a target tensor at a specific dim
tensor_a_unsqeeze = tensor_a_squeezed.unsqueeze(dim=0)
tensor_a_unsqeeze,tensor_a_unsqeeze.shape


(tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.]]), torch.Size([1, 9]))

In [ ]:
# torch.permute() - rearange the dimensions of an input tensor into a defined order
tensor_rand_3D = torch.rand(size=[640,640,3])
# Permute the tensor to rearrange the axis/dim order
tensor_rand_3D_permuted = torch.permute(tensor_rand_3D,dims=[2,0,1]) # Shifts dim/axis 0->1, 1->2, and 2->0
tensor_rand_3D_permuted.shape

torch.Size([3, 640, 640])

In [ ]:
tensor_rand_3D[0,0,0] = 0
tensor_rand_3D[0,0,0], tensor_rand_3D_permuted[0,0,0]

(tensor(0.), tensor(0.))

## Indexing (Selecting data from tensor)
Similar to Numpy

In [ ]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Extracting all values from 1st dim <=> dim=0
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Extracting the the first row of x
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# Extracting the second col of x
x[0,:,1]

tensor([2, 5, 8])

In [ ]:
from math import floor
# Extracting the center value of x
numChannels,numRows,numCols = x.shape
x[0,floor(x.shape[1]/2),floor(x.shape[2]/2)]

tensor(5)

## PyTorch tensor & Numpy
- Numpy array to PyTorch tensor -> `torch.from_numpy(ndarray)`

**Warning:** When converting from numpy to tensor, pytorch will use the numpy's default dtype (float64) unless specified otherwise

- Pytorch tensor to numpy array -> `torch.Tensor.numpy(tensor)` or `tensor.numpy()`

In [ ]:
array = np.arange(1.0,8.0)
tensor_np2tensor = torch.from_numpy(array)
tensor_np2tensor = tensor_np2tensor.type(torch.float32)
print(array.dtype)
print(tensor_np2tensor.dtype)

float64
torch.float32


In [ ]:
# Tensor to numpy array
tensor_tensor2np = torch.ones(7)
np_tensor2np = torch.Tensor.numpy(tensor_tensor2np)
np_tensor2np, np_tensor2np.dtype

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32), dtype('float32'))

## Reproducibility (trying to take random out of random)
To reduce the randomness in neural network and PyTorch comes the concept of a **random seed**

In [ ]:
# Create 2 random tensors
tensor_random_A = torch.rand(3,4)
tensor_random_B = torch.rand(3,4)

print(tensor_random_A)
print(tensor_random_B)
print(tensor_random_A == tensor_random_B)

tensor([[0.4059, 0.5760, 0.4456, 0.7205],
        [0.7771, 0.2699, 0.3025, 0.3030],
        [0.0683, 0.1807, 0.3939, 0.4961]])
tensor([[0.3402, 0.1334, 0.3733, 0.0893],
        [0.3615, 0.8885, 0.2698, 0.6732],
        [0.3540, 0.8697, 0.0697, 0.5952]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Create random but reproducible tensors

# Set a random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_random_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
tensor_random_D = torch.rand(3,4)

print(tensor_random_C)
print(tensor_random_D)
print(tensor_random_C == tensor_random_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Runing tensors and PyTorch objects on GPUs


### 1. Getting a GPU
1. Easiest - Use Google Colab for a free GPU
2. Personal GPU
3. Use cloud computing - GCP,AWS, Azure <=> Services allow you to rent computers on the cloud and access them

### 2. Checking GPU

In [ ]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (models) on the GPU

In [ ]:
# Create a tensor (default on GPU)
tensor = torch.tensor([1,2,3], device='cpu')

# tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if availible)
tensor_onGPU = tensor.to(device)
tensor_onGPU

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to CPU

In [ ]:
# If tensor is on GPU, can't transform it to numpy
# tensor_onGPU.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with np issue, we can first set it to cpu
tensor_back_onCPU = tensor_onGPU.cpu().numpy()
tensor_back_onCPU

array([1, 2, 3])